In [253]:
import torch
from torch import Tensor
import torch.nn as nn
import torch.nn.functional as F
from torch import optim
import dlc_practical_prologue as prologue

In [261]:
train_input, train_target, train_classes, test_input, test_target, test_classes = prologue.generate_pair_sets(5)

In [263]:
train_input.shape

torch.Size([5, 2, 14, 14])

In [269]:
a = torch.tensor([1,2,3,4,5,5,6])
a.split(2)

(tensor([1, 2]), tensor([3, 4]), tensor([5, 5]), tensor([6]))

In [266]:
a, b, c,\
d,e = 1,2,3,4,5

In [270]:
def train_model(model, train_input, train_target, train_classes):
    lr, nb_epochs, batch_size = 1e-1, 25, 10 
    
    optimizer = torch.optim.SGD(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    
    for e in range(nb_epochs):
        for inputs, targets in zip(train_input.split(batch_size),
                                  train_target.split(batch_size)):
            outputs = model(inputs)
            loss = criterion(output, targets)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

In [ ]:
def compute_nb_errors(model, data_input, data_target):
    
    nb_data_errors = 0
    batch_size = 10
    loss = 0
    for inputs in range(0, data_input.size(0), batch_size):
        output = model(data_input.narrow(0, b, batch_size))
        _, predicted_classes = torch.max(output, 1)
        for k in range(batch_size):
            if data_target[b + k] != predicted_classes[k]:
                nb_data_errors = nb_data_errors + 1

    return nb_data_errors, loss

In [ ]:
def eval_perf(model, nb_rounds=10, input_size=1000):
    avg_train_accuracy = []
    avg_test_accuracy = []
    for r in nb_rounds:
        train_input, train_target, train_classes,\ 
        test_input, test_target, test_classes = prologue.generate_pair_sets(input_size)
        train_model(model, train_input, train_target, train_classes)
        print("Round {0}".format(r))
        print("Training accuracy {0}".format(r))
        model(train_input)

In [105]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(2, 32, kernel_size=5)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=5)
        self.fc1 = nn.Linear(256, 200)
        self.fc2 = nn.Linear(200, 10)
        
    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), kernel_size=3, stride=3))
        x = F.relu(F.max_pool2d(self.conv2(x), kernel_size=2, stride=2))
        x = x.view(-1, 256)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [111]:
module = Net()
module(x)

tensor([[-0.0913, -0.0200,  0.0030, -0.0962,  0.1913,  0.1090,  0.0159,  0.0417,
          0.0241,  0.0448],
        [-0.0880, -0.0477,  0.0063, -0.1196,  0.1619,  0.1032, -0.0210,  0.0658,
          0.0362,  0.0040],
        [-0.1163, -0.0493, -0.0060, -0.1117,  0.1532,  0.0950,  0.0468,  0.1366,
         -0.0119,  0.0159],
        [-0.1413, -0.0545,  0.0027, -0.1181,  0.1299,  0.1808,  0.0483,  0.0795,
         -0.0469,  0.0661],
        [-0.1703,  0.0127, -0.0242, -0.1119,  0.1747,  0.1011,  0.0228,  0.0724,
          0.0114,  0.0539],
        [-0.1219, -0.0790,  0.0088, -0.0991,  0.1071,  0.1609,  0.0322,  0.1009,
         -0.0274, -0.0199],
        [-0.0518, -0.0594,  0.0035, -0.1751,  0.1587,  0.1651,  0.0621,  0.0630,
         -0.0473,  0.0549],
        [-0.0471, -0.0638, -0.0220, -0.0373,  0.1960,  0.1246,  0.0284,  0.0700,
         -0.0811,  0.0113],
        [-0.1037, -0.0716,  0.0247, -0.1047,  0.1670,  0.0667,  0.0698,  0.0788,
         -0.0129,  0.0317],
        [-0.0700, -

In [220]:
n = 10000
rand = 10
x1 = torch.empty(n,2).random_(rand)
y1 = torch.zeros(n)

x2 = torch.empty(n,2).random_(rand)
x2[:,0] = -x2[:,0]
y2 = torch.ones(n)
x3 = torch.empty(n,2).random_(rand)
x3[:int(len(x3)/2)] = -x3[:int(len(x3)/2)]
x3[int(len(x3)/2):, 1] = -x3[int(len(x3)/2):, 1]
a = np.array(x3)
np.random.shuffle(a)
x3 = torch.tensor(a)
y3 = torch.zeros(n) + 2

train_input = torch.cat((x1,x2,x3)).double()
train_target = torch.cat((y1,y2,y3)).double()

In [221]:
train_target.narrow(0, 6, mini_batch_size).long()

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [222]:
x1 = torch.empty(n,2).random_(rand)
y1 = torch.zeros(n)

x2 = torch.empty(n,2).random_(rand)
x2[:,0] = -x2[:,0]
y2 = torch.ones(n) 
x3 = torch.empty(n,2).random_(rand)
x3[:int(len(x3)/2)] = -x3[:int(len(x3)/2)]
x3[int(len(x3)/2):, 1] = -x3[int(len(x3)/2):, 1]
a = np.array(x3)
np.random.shuffle(a)
x3 = torch.tensor(a)
y3 = torch.ones(n) + 1

test_input = torch.cat((x1,x2,x3)).double()
test_target = torch.cat((y1,y2,y3)).double()

In [223]:
import numpy as np

In [245]:
model = nn.Sequential(nn.Linear(2,3))
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr = 1e-1)

mini_batch_size = 100
nb_epochs = 250
for e in range(nb_epochs):
    print(e)
    for b in range(0, train_input.size(0), mini_batch_size):
        output = model(train_input.narrow(0, b, mini_batch_size).float())
        loss = criterion(output, train_target.narrow(0, b, mini_batch_size).long())
        model.zero_grad()
        loss.backward()
        optimizer.step()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249


In [230]:
pred

tensor([0, 0, 0,  ..., 2, 2, 2])

In [239]:
len(predicted)

30000

In [246]:
predicted = model(test_input.float()).argmax(axis=1) 
(predicted != test_target).sum()

tensor(11069)

In [250]:
for m in model.parameters():
    print(m)

Parameter containing:
tensor([[-0.0689,  2.7824],
        [-0.1511,  3.6180],
        [-0.1273, -5.8546]], requires_grad=True)
Parameter containing:
tensor([-0.7896, -0.6637,  1.2921], requires_grad=True)


In [ ]:
prin

In [236]:
np.array([True]).sum()

0